name: Development Worfklow

on:
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'
      - 'hotfix/*'
      - 'main'
  workflow_dispatch:

jobs: 
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DEV_DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      # -run: supabase start
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase migration list
      # - run: supabase db diff --linked --debug
      - run: supabase db push
      - run: supabase migration list
