name: Staging Workflow

on:
  push:
    branches:
      - '*-maintenance'  # Matches branches in the format of <major>.<minor>-maintenance
  workflow_dispatch:


jobs:
  setup:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: echo "Staging Yay!"