name: Test Environment Worfklow

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs: 
  deploy_db_migrations:
    runs-on: ubuntu-latest
    
    env:
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DEV_DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase migration list
      # - run: supabase db diff --linked --debug
      - run: supabase db push
      - run: supabase migration list
  deploy_edge_functions:
    runs-on: ubuntu-latest
    
    env:
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase functions list
      - run: supabase functions deploy

