name: Test Environment Worfklow

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs: 
  unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: supabase/functions/tests
    env:
      SUPABASE_URL: http://localhost:54321
      SUPABASE_ANON_KEY: test-anon-key
      SPORTS_DATA_NBA_API_KEY: test-sports-key
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: Run unit tests
        run: deno test --allow-env --allow-read --allow-net --env-file=../.env
  deploy_db_migrations:
    runs-on: ubuntu-latest
    needs: unit_tests
    
    env:
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DEV_DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase migration list
      # - run: supabase db diff --linked --debug
      - run: supabase db push
      - run: supabase migration list
  deploy_edge_functions:
    runs-on: ubuntu-latest
    needs: unit_tests
    
    env:
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase functions list
      - run: supabase functions deploy

